genre:
- ''
- Album jeunesse
- Bande dessinée
- Essai
- Lettres
- Manga
- Nouvelle
- Poésie
- Roman
- Théâtre
format:
- ''
- Audio
- Numérique
- Papier
owner:
- ''
- Autre
- Bibliothèque
- Blanche
- Blanche et Eliot
- Eliot
langue:
- ''
- Anglais
- Espagnol
- Français
keywords:
- ''
- adaptation
- biographie
- classique
- épistolaire
- féminisme
- historique
- jeunesse
- lgbtqia+
- mashed-potato
- mémoires
- policier
- recueil
- romance
- sociologie
- sport
- ya
acqui_type:
- ''
- Achat
- Cadeau
- Emprunt
acqui_state:
- ''
- Neuf
- Occasion
langue_vo:
- ''
- Allemand
- Amharique
- Anglais
- Arabe
- Assamais
- Awadhi
- Azerbaïdjanais (Sud)
- Bengali
- Bhojpouri
- Biélorusse
- Birman
- Chhattisgarhi
- Chinois
- Chittagonian
- Coréen
- Deccan
- Espagnol
- Farsi
- Filipino
- Français
- Goudjarati
- Grec
- Haoussa
- Haryanvi
- Hindi
- Hongrois
- Ibo
- Indonésien
- Italien
- Japonais
- Javanais
- Kannada
- Madourais
- Magahi
- Maithili
- Malais
- Malayalam
- Marathi
- Marwari
- Néerlandais
- Népali
- Oriya
- Ourdou
- Ouzbek
- Pendjabi
- Polonais
- Portugais
- Roumain
- Russe
- Saraiki
- Serbe
- Sindhi
- Singhalais
- Suédois
- Sunda
- Tamoul
- Tchèque
- Telugu
- Thaï
- Turc
- Ukrainien
- Vietnamien
- Visayan
- Yorouba
- Zhuang
pays_vo:
- ''
- Afghanistan
- Afrique du Sud
- Albanie
- Algérie
- Allemagne
- Andorre
- Angleterre
- Angola
- Anguilla
- Antarctique
- Antigua-et-Barbuda
- Antilles Néerlandaises
- Arabie Saoudite
- Argentine
- Arménie
- Aruba
- Australie
- Autriche
- Azerbaïdjan
- Bahamas
- Bahreïn
- Bangladesh
- Barbade
- Bélarus
- Belgique
- Belize
- Bénin
- Bermudes
- Bhoutan
- Bolivie
- Bosnie-Herzégovine
- Botswana
- Brésil
- Brunéi Darussalam
- Bulgarie
- Burkina Faso
- Burundi
- Cambodge
- Cameroun
- Canada
- Cap-vert
- Chili
- Chine
- Chypre
- Colombie
- Comores
- Costa Rica
- Côte d'Ivoire
- Croatie
- Cuba
- Danemark
- Djibouti
- Dominique
- Écosse
- Égypte
- El Salvador
- Émirats Arabes Unis
- Équateur
- Érythrée
- Espagne
- Estonie
- États Fédérés de Micronésie
- États-Unis
- Éthiopie
- Fidji
- Finlande
- France
- Gabon
- Gambie
- Géorgie
- Géorgie du Sud et les Îles Sandwich du Sud
- Ghana
- Gibraltar
- Grèce
- Grenade
- Groenland
- Guadeloupe
- Guam
- Guatemala
- Guinée
- Guinée Équatoriale
- Guinée-Bissau
- Guyana
- Guyane Française
- Haïti
- Honduras
- Hong-Kong
- Hongrie
- Île Bouvet
- Île Christmas
- Île de Man
- Île Norfolk
- Îles (malvinas) Falkland
- Îles Åland
- Îles Caïmanes
- Îles Cocos (Keeling)
- Îles Cook
- Îles Féroé
- Îles Heard et Mcdonald
- Îles Mariannes du Nord
- Îles Marshall
- Îles Mineures Éloignées des États-Unis
- Îles Salomon
- Îles Turks et Caïques
- Îles Vierges Britanniques
- Îles Vierges des États-Unis
- Inde
- Indonésie
- Iran
- Iraq
- Irlande
- Islande
- Israël
- Italie
- Jamahiriya Arabe Libyenne
- Jamaïque
- Japon
- Jordanie
- Kazakhstan
- Kenya
- Kirghizistan
- Kiribati
- Koweït
- Lesotho
- Lettonie
- Liban
- Libéria
- Liechtenstein
- Lituanie
- Luxembourg
- Macao
- Macédoine
- Madagascar
- Malaisie
- Malawi
- Maldives
- Mali
- Malte
- Maroc
- Martinique
- Maurice
- Mauritanie
- Mayotte
- Mexique
- Monaco
- Mongolie
- Monténégro
- Montserrat
- Mozambique
- Myanmar
- Namibie
- Nauru
- Népal
- Nicaragua
- Niger
- Nigéria
- Niué
- Norvège
- Nouvelle-Calédonie
- Nouvelle-Zélande
- Oman
- Ouganda
- Ouzbékistan
- Pakistan
- Palaos
- Palestine
- Panama
- Papouasie-Nouvelle-Guinée
- Paraguay
- Pays de Galles
- Pays-Bas
- Pérou
- Philippines
- Pitcairn
- Pologne
- Polynésie Française
- Porto Rico
- Portugal
- Qatar
- République Arabe Syrienne
- République Centrafricaine
- République de Corée
- République de Moldova
- République Démocratique du Congo
- République Démocratique Populaire Lao
- République Dominicaine
- République du Congo
- République Populaire Démocratique de Corée
- République Tchèque
- République-Unie de Tanzanie
- Réunion
- Roumanie
- Royaume-Uni
- Russie
- Rwanda
- Sahara Occidental
- Saint-Kitts-et-Nevis
- Saint-Marin
- Saint-Pierre-et-Miquelon
- Saint-Siège (état de la Cité du Vatican)
- Saint-Vincent-et-les Grenadines
- Sainte-Hélène
- Sainte-Lucie
- Samoa
- Samoa Américaines
- Sao Tomé-et-Principe
- Sénégal
- Serbie
- Seychelles
- Sierra Leone
- Singapour
- Slovaquie
- Slovénie
- Somalie
- Soudan
- Sri Lanka
- Suède
- Suisse
- Suriname
- Svalbard et Île Jan Mayen
- Swaziland
- Tadjikistan
- Taïwan
- Tchad
- Terres Australes Françaises
- Territoire Britannique de l'Océan Indien
- Thaïlande
- Timor-Leste
- Togo
- Tokelau
- Tonga
- Trinité-et-Tobago
- Tunisie
- Turkménistan
- Turquie
- Tuvalu
- Ukraine
- Uruguay
- Vanuatu
- Venezuela
- Viet Nam
- Wallis et Futuna
- Yémen
- Zambie
- Zimbabwe
